using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Fesenmeier_Fujitsu.Models
{
    public class Movie
    {
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        // standard BSonId generated by MongoDb
        public string Id { get; set; }

        [Required]
        public string title { get; set; }

        public string director { get; set; }

        public string actors { get; set; }
        [Required]
        public int year { get; set; }

        public string image { get; set; }
    }
}
